# Generated by Django 5.0 on 2023-12-27 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 19, 0, 44, 967314), verbose_name='Дата публикации (по МСК)'),
        ),
    ]
