# Generated by Django 5.0 on 2023-12-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_url',
            field=models.URLField(max_length=120, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
