# Generated by Django 5.0 on 2023-12-17 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_course_id_alter_coursecategory_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'курсы', 'verbose_name_plural': 'курс'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': 'категории', 'verbose_name_plural': 'категория'},
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.coursecategory', verbose_name='Категория'),
        ),
    ]
