# Generated by Django 5.0.4 on 2024-04-25 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_course_category_alter_course_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 10, 28, 37, 264268), verbose_name='Дата публикации (по МСК)'),
        ),
    ]
