# Generated by Django 5.0.4 on 2024-04-25 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_course_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='product_url',
            field=models.URLField(default='', max_length=120, verbose_name='Ссылка на продукт (появится после оплаты)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_url',
            field=models.URLField(blank=True, default='', max_length=120, null=True, verbose_name='Ссылка на подробную информацию или сайт курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 20, 48, 41, 97840), verbose_name='Дата публикации (по МСК)'),
        ),
    ]
