# Generated by Django 5.0.4 on 2024-04-25 22:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_course_product_url_alter_course_course_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 1, 13, 50, 603513), verbose_name='Дата публикации (по МСК)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(100000)], verbose_name='Цена в рублях (миниммум 80, максимум 100 000)'),
        ),
    ]
