# Generated by Django 5.0.4 on 2024-04-26 00:39

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_course_datetime_alter_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(default='', max_length=60, verbose_name='Логин в Telegram')),
                ('product_id', models.CharField(default='', max_length=120, verbose_name='ID продукта')),
                ('product_name', models.CharField(default='', max_length=60, verbose_name='Название продукта')),
                ('product_url', models.URLField(default='', max_length=120, verbose_name='Ссылка на продукт')),
                ('product_paid', models.IntegerField(default=0, verbose_name='Оплачено за продукт (В рублях)')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 3, 39, 49, 368665), verbose_name='Дата публикации (по МСК)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(100000)], verbose_name='Цена в рублях'),
        ),
    ]
