# Generated by Django 5.0 on 2023-12-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_rename_coursecategory_coursecategories_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategories',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(default='', max_length=120, verbose_name='Название'),
        ),
    ]
