# Generated by Django 5.0.4 on 2024-04-26 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_purchase_alter_course_datetime_alter_course_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='product_id',
            new_name='product_pk',
        ),
        migrations.AlterField(
            model_name='course',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 3, 56, 20, 480897), verbose_name='Дата публикации (по МСК)'),
        ),
    ]
