# Generated by Django 5.0.4 on 2024-04-26 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_rename_product_id_purchase_product_pk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='product_pk',
            new_name='product_id',
        ),
        migrations.AlterField(
            model_name='course',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 4, 3, 46, 349841), verbose_name='Дата публикации (по МСК)'),
        ),
    ]
