# Generated by Django 5.0.4 on 2024-04-26 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_rename_product_pk_purchase_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='currency',
            field=models.CharField(default='', editable=False, max_length=60, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='course',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 4, 10, 9, 170739), verbose_name='Дата публикации (по МСК)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product_paid',
            field=models.IntegerField(default=0, verbose_name='Оплачено за продукт'),
        ),
    ]
