# Generated by Django 5.0 on 2023-12-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_courses_description_alter_courses_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='tags',
            field=models.CharField(default='', max_length=120, verbose_name='Теги'),
        ),
    ]
