# Generated by Django 5.0 on 2023-12-22 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_courses_description_alter_courses_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 22, 17, 56, 44, 941999), verbose_name='Дата публикации'),
        ),
    ]
