# Generated by Django 5.0 on 2023-12-22 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_courses_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
