# Generated by Django 5.0 on 2023-12-22 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_alter_courses_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 22, 18, 31, 23, 423877, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
    ]
