# Generated by Django 5.0 on 2023-12-22 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_alter_courses_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 22, 21, 50, 17, 847852), verbose_name='Дата публикации (по МСК)'),
        ),
    ]
