# Generated by Django 5.0 on 2023-12-22 19:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_alter_courses_datetime_alter_courses_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.coursecategories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 22, 22, 4, 34, 193944), verbose_name='Дата публикации (по МСК)'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Теги'),
        ),
    ]
