# Generated by Django 5.0 on 2023-12-22 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_courses_image_alter_courses_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 22, 22, 14, 35, 59485), verbose_name='Дата публикации (по МСК)'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
