# Generated by Django 5.0 on 2023-12-22 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_alter_courses_datetime_alter_courses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 0, 22, 11, 177426), verbose_name='Дата публикации (по МСК)'),
        ),
    ]
